steps:
- name: 'python'
  entrypoint: 'pip'
  args: ["install", "-r", "requirements.txt", "--user"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'bq query --nouse_legacy_sql --format=csv --max_rows=100000000 <get_progress.sql >progress.csv']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', './sync_with_api.py --out=result.jsonl --owners=tidbcloud --progress_file=progress.csv']
  secretEnv: ['GITHUB_TOKEN']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'bq load --source_format=NEWLINE_DELIMITED_JSON --format=json github.pull_requests_exp result.jsonl schema_extended.json']
availableSecrets:
  secretManager:
  - versionName: projects/27323915999/secrets/yunqing-github-cloudbuild/versions/1
    env: 'GITHUB_TOKEN'
timeout: 3600s
