steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'pip'
  args: ["install", "-r", "requirements.txt", "--user"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'bq query --nouse_legacy_sql --format=csv --max_rows=100000000 <get_progress.sql >progress.csv']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', './sync_with_api.py --out=result.jsonl --selectors=tidbcloud/*,pingcap/tidb-operator,pingcap/* --progress_file=progress.csv']
  secretEnv: ['GITHUB_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/27323915999/secrets/yunqing-github-cloudbuild/versions/latest
    env: 'GITHUB_TOKEN'
timeout: 3600s
